### ISSUE TITLE
distro for tutorial modules?

### ISSUE THREAD

**Issue by keturn** [Terasology/Index#15]
When we made sweeping changes for JOML and https://github.com/MovingBlocks/Terasology/pull/4560, we checked all the modules in Omega, but the tutorial modules did not get brought along for the ride, as the next batch of GSoC applicants discovered shortly after. (e.g. https://github.com/Terasology/TutorialWorldGeneration/pull/18 )

I think we've intentionally left the Tutorial modules out of Omega because they're not something we want to ship to players, but it's at least as important to not have regressions there as it is with everything else.

Should we have a distro of tutorials so we can include them when we do these API changes and have a view of them on CI?

**Comment by keturn** [comment]
We decided that since tutorial modules consistently start with `Tutorial*`, that is good enough as `groovyw module` supports wildcards.

**Comment by Cervator** [comment]
One drawback there though: being able to fetch all the modules easily is one thing. Keeping better track of them and when they break is another 🤔 That I'm less sure how to deal with. We could probably just make that cleaner view at a higher level in CI?

**Comment by keturn** [comment]
http://jenkins.terasology.io/teraorg/job/Terasology/job/Modules/view/Tutorials/

**Comment by Cervator** [comment]
@keturn nice! And wow, that's a lot of 🔴
