### ISSUE TITLE
Jenkins omega build has no versionInfo.properties artifact

### ISSUE THREAD

**Issue by keturn** [Terasology/Index#16]
Launcher relies on a `versionInfo.properties` artifact being published alongside the zip to be able to show metadata about it before downloading the whole distribution.

Problem **1**: The last few builds have produced zips but no accompanying versionInfo artifacts.

Problem **2**: this type of failure can go unnoticed for a bit, because a jenkins `archiveArtifacts` step is satisfied if _anything_ in its include list results in a file. It could have only zips, or even only an empty `md5sums.txt` file, and it wouldn't mark the build as failed or unstable.

**Comment by keturn** [comment]
Problem **2.a**: the distribution job gets the versionInfo.properties file via `copyArtifacts` from another job, and that lack of verification applies to the artifacts on the way in as well. So not only do we not notice when we fail to publish a thing, we also are oblivious if we failed to copy it in at the start.

**Comment by keturn** [comment]
This isn't the first time the path of that resource file has changed and it's broken something in the pipeline.

Which got me thinking: what if there were fewer artifacts to keep track of?

I tried adding this as a sh step to the Jenkinsfile:

```bash
set -e
cd distros/omega
unzip -j Terasology*.zip '**/engine-*.jar'
unzip -j engine-*.jar '**/versionInfo.properties'
```

It seems to [work](http://jenkins.terasology.io/teraorg/job/Nanoware/job/Iota/job/develop/10/execution/node/14/log/).

admittedly it does trade one kind of fragility (needing to change multiple jenkinsfiles any time this resource changes path) for a different kind of obscurity (needing to know how to dig that out of the guts of something within the distribution)

**Comment by skaldarnar** [comment]
Without the file there are currently only 3 distributions available via the launcher - so I'd greenlight any hotfix to bring the `versionInfo.properties` back :upside_down_face: 

I've shared my thoughts on [versioning game releases](https://discordapp.com/channels/270264625419911192/633681387995660303/839924598027059200) on Discord, incl. some options to get rid of the version file and consuming Jenkins builds altogether. https://github.com/MovingBlocks/Terasology/issues/4035 also contains some thoughts on release management and versions.

**Comment by keturn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Omega builds have no versionInfo](https://trello.com/c/Wci782ks/114-omega-builds-have-no-versioninfo)

**Comment by Cervator** [comment]
I plugged in the minimal fix for this - simple move of the file into an `engine` dir. Tests out.

I'm reluctant to change the _flavor_ of hack that makes up the build harness and Jenkins side build copying, since that's really what it all is at this point. It made sense years ago but we have way better tech today and should be able to do something vastly better overall. I'd like to see us focus on that while just minimally maintaining the working setup :-)

The zip trick could be part of that, I just think it deserves consideration as its own thing vs just being a tweak as part of a tiny fix.
